### ISSUE TITLE
Ticking entity crash

### ISSUE THREAD

**Issue by CDArena** [Team-Rapture/Modpack-Hypothermia#20]
I am slowly going back through my backups folder trying to find a working save to resume from; I have already increased RAM to 8GB with no improvement. The specific error seems to be caused by the ToughAsNails iceball, whatever that is (The blizzy looking thing? The floaty green things?)

java.lang.NullPointerException: Ticking entity
	at toughasnails.core.ClientProxy.spawnParticle(ClientProxy.java:93)
	at toughasnails.entities.projectile.EntityIceball.func_70071_h_(EntityIceball.java:223)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at toughasnails.core.ClientProxy.spawnParticle(ClientProxy.java:93)
	at toughasnails.entities.projectile.EntityIceball.func_70071_h_(EntityIceball.java:223)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
	at net.minecraft.world.World.func_72870_g(World.java:1934)

-- Entity being ticked --
Details:
	Entity Type: ToughAsNails.iceball (toughasnails.entities.projectile.EntityIceball)
	Entity ID: 34
	Entity Name: entity.ToughAsNails.iceball.name

**Comment by CDArena** [comment]
Note - this is a pre-existing game of hypothermia;
Increased RAM to 8GB - still get error.
Tried the last three saves - still get the error.
Now trying to delete and re-install the Hypothermia profile itself.
Same result.
Increased RAM to 8GB
Same result.
Trying 4th backup from days ago.

**Comment by CDArena** [comment]
Old backup on new profile worked - lost a bunch of progress though. Because of this "ticking entity - iceball" error that appears to affect the world save itself, I now switch to Peaceful mode before saving.

**Comment by EPIICTHUNDERCAT** [comment]
@CDArena Totally late, sorry I didnt see this! glad you are fixed
